#include "../ble_locator_i.h"
#include "ble_scene.h"

static const char* const bl_about_text =
    "BLE Locator\n"
    "Group and find BLE devices\n"
    "\n"
    "The app ships with no groups\n"
    "at all. It knows nothing until\n"
    "you teach it from real devices.\n"
    "\n"
    "HOW IT WORKS\n"
    "Almost anything with Bluetooth\n"
    "LE advertises itself constantly:\n"
    "scooters, tags, headphones,\n"
    "phones, laptops. This app\n"
    "listens, and lets you capture a\n"
    "few devices that belong\n"
    "together. It keeps only the\n"
    "traits they all share and turns\n"
    "that into a group, so it can\n"
    "recognise devices of the same\n"
    "kind it has never seen before.\n"
    "\n"
    "THE LIST HOLDS STILL\n"
    "Every scan opens with a few\n"
    "seconds of Scanning candidates.\n"
    "Stand where you want to look\n"
    "from and let it finish: what it\n"
    "hears goes into the list closest\n"
    "first, and those rows then keep\n"
    "their places. Only the signal\n"
    "numbers move after that, so a\n"
    "row you are aiming at stays put.\n"
    "\n"
    "Devices that turn up later are\n"
    "added by their signal, so\n"
    "walking into range of something\n"
    "new still shows it.\n"
    "\n"
    "Hold Left to re-scan and re-sort\n"
    "from wherever you are standing\n"
    "now. Settle time (3-10 s) is in\n"
    "Settings.\n"
    "\n"
    "SCAN ALL DEVICES\n"
    "Everything on air, strongest\n"
    "first, known groups labelled.\n"
    "This is the mode for working out\n"
    "what is around you.\n"
    "\n"
    "FIND A GROUP\n"
    "Pick a group and the screen\n"
    "stays empty until a member of it\n"
    "comes into range. Any group\n"
    "means \"anything I have taught\n"
    "you, nothing else\".\n"
    "OK on a row opens the homing\n"
    "screen: the beeps get faster as\n"
    "you close in and it vibrates\n"
    "within a metre or two.\n"
    "\n"
    "LEARN A GROUP\n"
    "1. Menu > Learn a group\n"
    "2. Stand next to a device you\n"
    "   want in the group. It should\n"
    "   be at the top of the list.\n"
    "3. Press OK to capture it.\n"
    "4. Repeat on 3-5 different units\n"
    "   of the same kind. More\n"
    "   captures = a sharper\n"
    "   fingerprint, because only the\n"
    "   traits they all share are\n"
    "   kept.\n"
    "5. Press Right to build. The\n"
    "   review screen scores the\n"
    "   group against everything else\n"
    "   on air and says whether it\n"
    "   actually singles them out.\n"
    "6. Name it and save.\n"
    "\n"
    "BUILDING A GROUP OVER TIME\n"
    "You do not have to meet every\n"
    "device in one sitting. A group\n"
    "keeps the devices it was built\n"
    "from, so you can come back to\n"
    "it whenever you run into\n"
    "another one.\n"
    "\n"
    "Groups > pick one:\n"
    "  Add device  scans, you pick\n"
    "              one, the group\n"
    "              is rebuilt\n"
    "  Members     the devices it\n"
    "              was built from;\n"
    "              open one to\n"
    "              remove it\n"
    "\n"
    "Either way the review screen\n"
    "scores the result before you\n"
    "keep it, so you can see a\n"
    "wrong device widening the\n"
    "group and back out.\n"
    "\n"
    "Groups learned before this\n"
    "existed have no members kept\n"
    "and start their list from the\n"
    "first device you add.\n"
    "\n"
    "KEYS\n"
    "Up/Down  move\n"
    "OK       capture (learn) or\n"
    "         home in (find)\n"
    "Left     undo last capture\n"
    "Hold Left  re-scan, re-sort\n"
    "Right    build (learn) or\n"
    "         details (find)\n"
    "Hold OK  raw advert and\n"
    "         per-group scores\n"
    "\n"
    "TIPS\n"
    "- Signal strength is direction\n"
    "  blind. Walk, watch the trend,\n"
    "  and sweep around obstacles.\n"
    "- Survey log writes every packet\n"
    "  to apps_data/ble_locator/\n"
    "  survey.csv for later analysis.\n"
    "- Groups live in groups.txt in\n"
    "  the same folder and can be\n"
    "  edited or copied between\n"
    "  devices.\n"
    "\n"
    "REQUIREMENTS\n"
    "The full BLE radio stack must be\n"
    "installed (the stock light stack\n"
    "cannot receive adverts at all).\n";

void ble_scene_about_on_enter(void* context) {
    BlApp* app = context;

    widget_reset(app->widget);
    widget_add_text_scroll_element(app->widget, 0, 0, 128, 64, bl_about_text);

    view_dispatcher_switch_to_view(app->view_dispatcher, BlViewIdWidget);
}

bool ble_scene_about_on_event(void* context, SceneManagerEvent event) {
    UNUSED(context);
    UNUSED(event);
    return false;
}

void ble_scene_about_on_exit(void* context) {
    BlApp* app = context;
    widget_reset(app->widget);
}
